<h1>Horizontal Vector</h1>

In [1]:
import numpy as np 
 
lst = [10,20,30,40,50] 
 
vctr = np.array(lst) 
 
vctr = np.array(lst) 
 
print("Vector created from a list:") 
print(vctr)

Vector created from a list:
[10 20 30 40 50]


<h1>Vertical Vector

</h1>

In [2]:
import numpy as np 
 
lst = [[2], 
        [4], 
        [6],
          [10]]  
 
vctr = np.array(lst) 
 
vctr = np.array(lst) 
 
print("Vector created from a list:") 
print(vctr)

Vector created from a list:
[[ 2]
 [ 4]
 [ 6]
 [10]]


<h1>Vector Ops</h1>

In [3]:
#Addition
import numpy as np 
 
lst1 = [10,20,30,40,50] 
lst2 = [1,2,3,4,5]
 
 
vctr1 = np.array(lst1) 
 
vctr2= np.array(lst2) 
 
 
print("Vector created from a list 1:") 
print(vctr1) 
print("Vector created from a list 2:") 
print(vctr2) 
 
vctr_add = vctr1+vctr2
print("Addition of two vectors: ",vctr_add)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Addition of two vectors:  [11 22 33 44 55]


In [4]:
#Substraction
import numpy as np 
 
lst1 = [10,20,30,40,50] 
lst2 = [1,2,3,4,5]
 
vctr1 = np.array(lst1) 
 
vctr2= np.array(lst2) 
 
print("Vector created from a list 1:") 
print(vctr1) 
print("Vector created from a list 2:") 
print(vctr2) 
 
vctr_sub = vctr1-vctr2
print("Subtraction of two vectors: ",vctr_sub)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Subtraction of two vectors:  [ 9 18 27 36 45]


In [5]:
#Muliplication
import numpy as np 
 
lst1 = [10,20,30,40,50] 
lst2 = [1,2,3,4,5]
 
vctr1 = np.array(lst1) 
 
vctr2= np.array(lst2) 
 
print("Vector created from a list 1:") 
print(vctr1) 
print("Vector created from a list 2:") 
print(vctr2) 
 
vctr_mul = vctr1*vctr2
print("Multiplication of two vectors: ",vctr_mul)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Multiplication of two vectors:  [ 10  40  90 160 250]


In [6]:
#Division
import numpy as np 
  
lst1 = [10,20,30,40,50] 
lst2 = [10,20,30,40,50]
  
vctr1 = np.array(lst1) 
  
vctr2= np.array(lst2) 
  
print("Vector created from a list 1:") 
print(vctr1) 
print("Vector created from a list 2:") 
print(vctr2) 
  
vctr_div = vctr1/vctr2
print("Division of two vectors: ",vctr_div)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[10 20 30 40 50]
Division of two vectors:  [1. 1. 1. 1. 1.]


In [7]:
#Dot Prod
import numpy as np 
 
lst1 = [10,20,30,40,50] 
lst2 = [1,1,1,1,1]
 
 
vctr1 = np.array(lst1) 
 
vctr2= np.array(lst2) 
 
 
print("Vector created from a list 1:") 
print(vctr1) 
print("Vector created from a list 2:") 
print(vctr2) 
 
vctr_dot = vctr1.dot(vctr2)
print("Dot product of two vectors: ",vctr_dot)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 1 1 1 1]
Dot product of two vectors:  150
